language: ruby
rvm:
  - 1.9.3

gemfile: gemfiles/Gemfile.ci

script:
  - bundle update
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
